CREATE TABLE `page_log` (
  `pk` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `no` mediumint(8) unsigned NOT NULL,
  `msg` varchar(128) NOT NULL,
  `caller` varchar(128) DEFAULT NULL,
  `phone` int(10) unsigned DEFAULT NULL,
  `within` tinyint(3) unsigned DEFAULT NULL,
  `patient` varchar(128) DEFAULT NULL,
  `nhi` char(7) DEFAULT NULL,
  `ward` varchar(128) DEFAULT NULL,
  `bed` varchar(128) DEFAULT NULL,
  `why` varchar(128) DEFAULT NULL,
  `details` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `no` (`no`),
  KEY `phone` (`phone`),
  KEY `nhi` (`nhi`),
  KEY `ward` (`ward`),
  KEY `bed` (`bed`),
  KEY `why` (`why`),
  FULLTEXT KEY `msg` (`msg`),
  FULLTEXT KEY `patient` (`patient`),
  FULLTEXT KEY `details` (`details`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8
